# Generated by Django 2.1.4 on 2019-04-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование журнала')),
                ('issn', models.CharField(blank=True, max_length=64, verbose_name='ISSN')),
                ('description', models.TextField(blank=True, verbose_name='О журнале')),
                ('rkn_certificate_scan', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Сканы сертификатов')),
                ('redactor', models.CharField(blank=True, max_length=128, verbose_name='Редактор')),
                ('issue_period', models.CharField(blank=True, max_length=32, verbose_name='Периодисность издания')),
                ('issuer', models.CharField(blank=True, max_length=64, verbose_name='Издатель')),
                ('email', models.EmailField(blank=True, max_length=96, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
