# Generated by Django 2.1.4 on 2019-04-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование серии')),
                ('description', models.TextField(blank=True, verbose_name='О серии')),
            ],
        ),
        migrations.AlterField(
            model_name='journal',
            name='address',
            field=models.TextField(blank=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='series',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Journal'),
        ),
    ]
