# Generated by Django 2.1.4 on 2019-04-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Issue'),
        ),
    ]
