# Generated by Django 2.1.4 on 2019-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190416_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
