# Generated by Django 2.1.4 on 2019-04-16 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190416_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
