# Generated by Django 2.1.4 on 2019-04-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='publication_date',
            field=models.DateField(blank=True, verbose_name='Дата публикации'),
        ),
    ]
