# Generated by Django 2.1.4 on 2019-04-18 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190418_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='publication_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
