# Generated by Django 2.1.4 on 2019-04-18 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190418_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='publication_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации ГГГГ-ММ-ДД'),
        ),
    ]
